Repository heyimShivam/Algorithm, pull requests merged in 2022-10, with the labels that each got.

#7 Insertion Sort
  Insertion Sort.cpp
Labels: Hacktoberfest

#6 Merge Sort || C++|| O(nlogn)
  merge_sort.cpp
Labels: Hacktoberfest, hacktoberfest-accepted

#21 Quick Sort || C++ || O(n^2)
  quick_sort.cpp
Labels: Hacktoberfest, hacktoberfest-accepted

#37 Added Bubble Sort
  bubbleSort.cpp
Labels: Hacktoberfest, hacktoberfest-accepted

#34 Interpolation Search || C++ || O(n)
  interpolation_search.cpp
Labels: Hacktoberfest, hacktoberfest-accepted

#36 main
  Binary_Search.cpp
Labels: Hacktoberfest, hacktoberfest-accepted

#38 Longest Path In Matrix
  Longest Path In Matrix.cpp
Labels: Hacktoberfest, hacktoberfest-accepted

#39 created linear-search algorithm
  linear_search.cpp
Labels: Hacktoberfest, hacktoberfest-accepted

#41 Longest common subsequence || C++ || O(n^2)
  lcs.cpp
Labels: Hacktoberfest, hacktoberfest-accepted

#42 braedth_first_search added
  Breadth_first_search.cpp
Labels: Hacktoberfest, hacktoberfest-accepted

#46 Intro to CPP
  Intro/arrayAsParameter.cpp
  Intro/parameterPassing.cpp
  Intro/pointerstruct.cpp
  Intro/structure.c
Labels: Hacktoberfest, hacktoberfest-accepted

#47 Encrypt decrypt example
  radix sort.cpp
Labels: Hacktoberfest, hacktoberfest-accepted

#45 Added a python code for Quick sort algorithm
  quickSort.py
Labels: Hacktoberfest, hacktoberfest-accepted

#43 fibonaaci seach added
  Fibonacci_Series.cpp
Labels: Hacktoberfest, hacktoberfest-accepted

#44 0 1 knapsack .cpp
  01 knapsack .cpp
  subset sum problem
Labels: Hacktoberfest, hacktoberfest-accepted

#49 Add closest pair algorithm
  closest_pair.cpp
Labels: Hacktoberfest, hacktoberfest-accepted

#51 create DFS Search
  Depth_First_Search.cpp
Labels: Hacktoberfest, hacktoberfest-accepted

#50 added codes for both bucket and counting sorting techniques.
  bucketsort.cpp
  coutingsort.cpp
Labels: Hacktoberfest, hacktoberfest-accepted

#52 added backtracking problems
  backtracking/knightstour.cpp
  backtracking/ratinamaze.cpp
  dividenconquer.cpp
  naivealgo.cpp
Labels: Hacktoberfest, hacktoberfest-accepted

#53 Create Dijkstra's SHORTEST PATH ALGO
  Dijkstra's
Labels: Hacktoberfest, hacktoberfest-accepted

#57 Create Linear search algorithm
  Linear search algorithm
Labels: Hacktoberfest, hacktoberfest-accepted

#55 added naive algorithm
  patternsearching/naivealgo.cpp
Labels: Hacktoberfest, hacktoberfest-accepted

#65 Added Jump Search
  jump_search.cpp
Labels: Hacktoberfest, hacktoberfest-accepted

#64 all the negative elements will be placed at one side of array
  backtracking/mazeProblem.cpp
  happyNumber.cpp
  negativeOneSide.cpp
  slidingWindow.cpp
Labels: Hacktoberfest, hacktoberfest-accepted

#61 Added BFS Algorithm
  bfsTraversal.cpp
Labels: Hacktoberfest, hacktoberfest-accepted

#60 Create Heap sort .cpp
  Heap sort .cpp
Labels: Hacktoberfest, hacktoberfest-accepted

#59 Counting_Sort.cpp
  Counting_Sort.cpp
Labels: Hacktoberfest, hacktoberfest-accepted

#56 Longest Common Subsequence
  Longest-Common-Subsequence.cpp
Labels: Hacktoberfest, hacktoberfest-accepted

#63 Added BogoSort
  bogosort.cpp
Labels: Hacktoberfest, hacktoberfest-accepted

#66 added floyd warshall algorithm
  Floyd Warshall Algorithm
Labels: Hacktoberfest, hacktoberfest-accepted

#77 Added code for nested recursion.
  nested_recursion.cpp
Labels: Hacktoberfest, hacktoberfest-accepted

#76 Prims algorithm
  prims_algorithm.cpp
  toeplitzTriangle.cpp
Labels: Hacktoberfest, hacktoberfest-accepted

#73 Solution to LC 72. Edit Distance
  Edit_Distance.cpp
Labels: Hacktoberfest, hacktoberfest-accepted

#72 Create Binary Search using pthread
  Binary Search using pthread
Labels: Hacktoberfest, hacktoberfest-accepted

#71 Create Bitwise Sieve
  Bitwise Sieve
Labels: Hacktoberfest, hacktoberfest-accepted

#70 Create Segmented Sieve
  Segmented Sieve
Labels: Hacktoberfest, hacktoberfest-accepted

#69 Create LCA in a tree using Binary Lifting Technique
  LCA in a tree using Binary Lifting Technique
Labels: Hacktoberfest, hacktoberfest-accepted

#68 Kahn's algorithm for topo sort
  Kahn's algorithm for topo sort
Labels: Hacktoberfest, hacktoberfest-accepted

#67 added vertical order traversal of binary tree
  KMP Algorithm for pattern Searching
  KMP algorithm for pattern searching
  vertical order traversal of binary tree
Labels: Hacktoberfest, hacktoberfest-accepted

#78 Shell sort
  shellSort.cpp
Labels: Hacktoberfest, hacktoberfest-accepted

#79 Linear Search algorithm
  LinearSearchAlgorithm.cpp
Labels: Hacktoberfest, hacktoberfest-accepted

#82 Print all permutation of String
  Print_all_permutation_of_String.cpp
Labels: Hacktoberfest, hacktoberfest-accepted

#84 0-1 Knapsack Problem
  0-1 Knapsack Problem.cpp
Labels: Hacktoberfest, hacktoberfest-accepted

#89 Z algorithm (Linear time pattern searching Algorithm)
  Z algorithm (Linear time pattern searching Algorithm)
Labels: Hacktoberfest, hacktoberfest-accepted

#88 Spiral Matrix
  spiralMatrix.cpp
Labels: Hacktoberfest, hacktoberfest-accepted

#87 added Edit Distace - DP Problem
  DP/Edit Distance.cpp
Labels: Hacktoberfest, hacktoberfest-accepted

#86 Shell and Counting Sort Codes
  Shell Sort.cpp
  counting Sort.cpp
Labels: Hacktoberfest, hacktoberfest-accepted

#85 Create Reverse_string.cpp
  Reverse_string.cpp
Labels: Hacktoberfest, hacktoberfest-accepted

#95 Tree Programs (DSA)
  inorder binary tree.cpp
  level_order_traversal.cpp
  print_nodeat_k_distance.cpp
Labels: Hacktoberfest, hacktoberfest-accepted

#99 breadth first search algorithm
  breadth first search algo.cpp
  fibonacci search.cpp
Labels: Hacktoberfest, hacktoberfest-accepted

#97 Subset Sum Problem
  subsetSum.cpp
Labels: Hacktoberfest, hacktoberfest-accepted

#102 Program for nth Catalan Number hacktoberfest-2022
  DP/FriendsPairingProblem.cpp
  DP/nthCatalnNumber.cpp
Labels: Hacktoberfest, hacktoberfest-accepted

#105 Create tree-traversal.cpp
  tree-traversal.cpp
Labels: Hacktoberfest, hacktoberfest-accepted

#104 Create GoldMineProblem.cpp
  DP/GoldMineProblem.cpp
Labels: Hacktoberfest, hacktoberfest-accepted

#103 Create BinomialCofficient.cpp
  DP/BinomialCofficient.cpp
Labels: Hacktoberfest, hacktoberfest-accepted

#90 RobinRound.cpp
  RobinRound.cpp
Labels: Hacktoberfest, hacktoberfest-accepted

#106 Create Kruskal's_Algorithm.cpp
  Kruskal's_Algorithm.cpp
Labels: Hacktoberfest, hacktoberfest-accepted

#107 Dynamic Programming for find Pairs in array
  pairs.cpp
Labels: Hacktoberfest, hacktoberfest-accepted

#108 Advance Euclid Algorithm
  Advance_Euclid_Algorithm.cpp
Labels: Hacktoberfest, hacktoberfest-accepted

#120 Create Range maximum query using Sparse Table
  Range maximum query using Sparse Table
Labels: Hacktoberfest, hacktoberfest-accepted

#119 Create Segment Tree | Set 2 (Range Maximum Query with Node Update)
  Segment Tree | Set 2 (Range Maximum Query with Node Update)
Labels: Hacktoberfest, hacktoberfest-accepted

#118 Create LCE | Set 3 (Segment Tree Method)
  Longest Common Extension/LCE | Set 3 (Segment Tree Method)
Labels: Hacktoberfest, hacktoberfest-accepted

#117 Create Persistent Segment Tree
  Persistent Segment Tree
Labels: Hacktoberfest, hacktoberfest-accepted

#116 Combinational sum
  combinationSum.cpp
Labels: Hacktoberfest, hacktoberfest-accepted

#115 Minimum increment operations to make K elements equal
  MinimumIncrementOperationsTomakeKelementsEqual.cpp
Labels: Hacktoberfest, hacktoberfest-accepted

#114 Selection Sort
  selectionSort.cpp
Labels: Hacktoberfest, hacktoberfest-accepted

#112 DynamicMethod.java
  OOPS/DynamicMethod.java
Labels: Hacktoberfest, hacktoberfest-accepted

#111 Polymorphism.java
  OOPS/Polymorphism.java
Labels: Hacktoberfest, hacktoberfest-accepted

#110 InheritanceConcept.java
  OOPS/InhertanceConcept.java
Labels: Hacktoberfest, hacktoberfest-accepted

#109 Overloadling.java
  OOPS/Overloadling.java
Labels: Hacktoberfest, hacktoberfest-accepted

#131 Create DSU (Disjoint Set Union)
  DSU (Disjoint Set Union)
Labels: Hacktoberfest, hacktoberfest-accepted

#130 Create LCA (Sparse Matrix DP Approach)
  LCA (Sparse Matrix DP Approach)
Labels: Hacktoberfest, hacktoberfest-accepted

#129 Create Dynamic Segment Trees : Online Queries for Range Sum with Poin…
  Dynamic Segment Trees : Online Queries for Range Sum with Point Updates
Labels: Hacktoberfest, hacktoberfest-accepted

#128 Create Tries(Search_and_Insert)
  Tries(Search_and_Insert)
Labels: Hacktoberfest, hacktoberfest-accepted

#127 Create Count of Ks in the Array for a given range of indices after ar…
  Count of Ks in the Array for a given range of indices after array updates for Q queries
Labels: Hacktoberfest, hacktoberfest-accepted

#126 Create Digit DP(sum_of_all_digits_in_a_range)
  Digit DP(sum_of_all_digits_in_a_range)
Labels: Hacktoberfest, hacktoberfest-accepted

#125 Create Queries to find the Lower Bound of K from Prefix Sum Array wit…
  Queries to find the Lower Bound of K from Prefix Sum Array with updates using Fenwick Tree
Labels: Hacktoberfest, hacktoberfest-accepted

#124 Create SubarraySumEqualsK
  SubarraySumEqualsK
Labels: Hacktoberfest, hacktoberfest-accepted

#123 fibonacci_series.java
  fibonacci_series.java
Labels: Hacktoberfest, hacktoberfest-accepted

#122 Quadratic Probing
  Quadratic Probing
Labels: Hacktoberfest, hacktoberfest-accepted

#121 Chaining.cpp
  Chaining.cpp
Labels: Hacktoberfest, hacktoberfest-accepted

#132 Create Segment Trees | (Product of given Range Modulo m)
  Segment Trees | (Product of given Range Modulo m)
Labels: Hacktoberfest, hacktoberfest-accepted

#133 Create BinaryTree MaximumPathSum
  BinaryTree MaximumPathSum
Labels: Hacktoberfest, hacktoberfest-accepted

#136 Create Number of LongestIncreasingSubsequence
  Number of LongestIncreasingSubsequence
Labels: Hacktoberfest, hacktoberfest-accepted

#135 Create Sum of Distances in Tree
  Sum of Distances in Tree
Labels: Hacktoberfest, hacktoberfest-accepted

#134 Create C++ Program to Find array sum using Bitwise OR after splitting…
  C++ Program to Find array sum using Bitwise OR after splitting given array in two halves after K circular shifts
Labels: Hacktoberfest, hacktoberfest-accepted

#150 Create Q String with additive sequence |kfj
  Q String with additive sequence |kfj
Labels: duplicate, Hacktoberfest, hacktoberfest-accepted

#159 Create flattering_linkedlist.cpp
  flattering_linkedlist.cpp
Labels: Hacktoberfest, hacktoberfest-accepted

#158 Create Counting Numbers CSES
  Counting Numbers CSES
Labels: Hacktoberfest, hacktoberfest-accepted

#157 Create Boring Numbers
  Boring Numbers
Labels: Hacktoberfest, hacktoberfest-accepted

#156 Create Digit Sum Spoj
  Digit Sum Spoj
Labels: Hacktoberfest, hacktoberfest-accepted

#155 Create Minimum Window Substring
  Minimum Window Substring
Labels: Hacktoberfest, hacktoberfest-accepted

#152 Create Find the last player to be able to flip a character in a Binar…
  Find the last player to be able to flip a character in a Binary String -  cbmv
Labels: Hacktoberfest, hacktoberfest-accepted

#149 Create q2 Find extra node in the second Linked list 8623
  q2 Find extra node in the second Linked list 8623
Labels: Hacktoberfest, hacktoberfest-accepted

#148 Create Segment Tree | (Sum of given range)xc
  Segment Tree | (Sum of given range)xc
Labels: Hacktoberfest, hacktoberfest-accepted

#147 Create Minimize flips to make binary string as all 1s by flipping cha…
  Minimize flips to make binary string as all 1s by flipping characters in substring of size K repeatedly
Labels: Hacktoberfest, hacktoberfest-accepted

#153 Create Couples Holding Hands mbj
  Couples Holding Hands mbj
Labels: Hacktoberfest, hacktoberfest-accepted

#154 Create Evaluate Reverse Polish Notation
  Evaluate Reverse Polish Notation
Labels: Hacktoberfest, hacktoberfest-accepted

#141 Added Prim’s algorithm in C++
  Prims.cpp
Labels: Hacktoberfest, hacktoberfest-accepted

#146 Create Maximize count of unique Squares that can be formed with N arb…
  Maximize count of unique Squares that can be formed with N arbitrary points in coordinate plane
Labels: Hacktoberfest, hacktoberfest-accepted

#145 Create Minimize rope length to connect given points in a 3D plane
  Minimize rope length to connect given points in a 3D plane
Labels: Hacktoberfest, hacktoberfest-accepted

#161 Create m_coloring_problem.cpp
  backtracking/m_coloring_problem.cpp
Labels: Hacktoberfest, hacktoberfest-accepted

#144 Create Generate lexicographically smallest Permutation of 1 to N wher…
  Generate lexicographically smallest Permutation of 1 to N where elements follow given relation
Labels: Hacktoberfest, hacktoberfest-accepted

#143 Diameter-Binary-Tree.cpp
  Diameter-of-a-Binary-Tree
Labels: Hacktoberfest, hacktoberfest-accepted

#142 Zig-Zag-Traversal.cpp
  Zig-Zag-Traversal
Labels: Hacktoberfest, hacktoberfest-accepted

#140 Create Number of decimal numbers of length k, that are strict monotone
  Number of decimal numbers of length k, that are strict monotone
Labels: Hacktoberfest, hacktoberfest-accepted

#139 Create Count ways to build street under given constraints
  Count ways to build street under given constraints
Labels: Hacktoberfest, hacktoberfest-accepted

#138 Create Golomb sequence
  Golomb sequence
Labels: Hacktoberfest, hacktoberfest-accepted

#166 STL_find_max_min_vector.cpp
  STL_find_max_min_vector.cpp
Labels: Hacktoberfest, hacktoberfest-accepted

#164 dnf_sort.cpp
  dnf_sort.cpp
Labels: Hacktoberfest, hacktoberfest-accepted

#163 append_k_nodes_to_start_of_linked_list.cpp
  append_k_nodes_to_start_of_linked_list.cpp
Labels: Hacktoberfest, hacktoberfest-accepted

#162 Create Coin change-2
  Coin change-2
Labels: Hacktoberfest, hacktoberfest-accepted

#169 Rabin Karp Algorithm
  Naive pattern.cpp
  Rabin karp algorithm.cpp
  fish pattern.cpp
  optimized kmp.cpp
Labels: Hacktoberfest, hacktoberfest-accepted

#167 Create heap_sort.cpp
  heap_sort.cpp
Labels: Hacktoberfest, hacktoberfest-accepted

#170 Create Palindrome-check.cpp
  Palindrome-check.cpp
Labels: Hacktoberfest, hacktoberfest-accepted

#176 Minimum Product Subset of an Array
  minimumProductSubSetArray.cpp
Labels: Hacktoberfest, hacktoberfest-accepted

#175 Add two bit strings
  AddTwoBitStrings.cpp
Labels: Hacktoberfest, hacktoberfest-accepted

#174 Code explaining about exponential search
  exponentialSearch.cpp
  mergeSort.cpp
Labels: Hacktoberfest, hacktoberfest-accepted

#172 Create Matrix-multiplication.cpp
  Matrix-multiplication.cpp
Labels: Hacktoberfest, hacktoberfest-accepted

#171 fish pattern using cpp
  Boyer  Moore algo.cpp
  Z - algorithm .cpp
  fish pattern.cpp
  naive pattern.cpp
Labels: Hacktoberfest, hacktoberfest-accepted

#185 trie of all suffix
  trie of all suffix.cpp
Labels: Hacktoberfest, hacktoberfest-accepted

#183 Create Huffman_coding.cpp
  Huffman_coding.cpp
Labels: Hacktoberfest, hacktoberfest-accepted

#182 Create Job Sequencing Problem
  Job Sequencing Problem
Labels: Hacktoberfest, hacktoberfest-accepted

#181 Create Egyptian Fraction
  Egyptian Fraction
Labels: Hacktoberfest, hacktoberfest-accepted

#180 Create activitySelectionProblem.cpp
  activitySelectionProblem.cpp
Labels: Hacktoberfest, hacktoberfest-accepted

#179 Create quicksort.cpp
  quicksort.cpp
Labels: Hacktoberfest, hacktoberfest-accepted

#177 Create Polymorphism.cpp
  Polymorphism.cpp
Labels: Hacktoberfest, hacktoberfest-accepted

#189 Create Kahn's Algorithm
  Kahn's Algorithm
Labels: Hacktoberfest, hacktoberfest-accepted

#188 Create KMP Algorithm
  KMP Algorithm
Labels: Hacktoberfest, hacktoberfest-accepted

#187 count of number of string
  count of number of string.cpp
Labels: Hacktoberfest, hacktoberfest-accepted

#186 Create A*.cpp
  A*.cpp
Labels: Hacktoberfest, hacktoberfest-accepted

#190 Create LCS using DP
  LCS using DP
Labels: Hacktoberfest, hacktoberfest-accepted

#191 Create Tarjan's Algorithm
  Tarjan's Algorithm
Labels: Hacktoberfest, hacktoberfest-accepted

#198 Create computeXORFrom1toN.cpp
  computeXORFrom1toN.cpp
Labels: Hacktoberfest, hacktoberfest-accepted

#197 Create N queen Problem (using Backtracking)
  N queen Problem (using Backtracking)
Labels: Hacktoberfest, hacktoberfest-accepted

#196 Create Extended Euclid algorithm
  Extended Euclid algorithm
Labels: Hacktoberfest, hacktoberfest-accepted

#195 Create Kadane's algorithm
  Kadane's algorithm
Labels: Hacktoberfest, hacktoberfest-accepted

#194 Create Z algorithm
  Z algorithm
Labels: Hacktoberfest, hacktoberfest-accepted

#193 Create Sieve of Eratosthenes
  Sieve of Eratosthenes
Labels: Hacktoberfest, hacktoberfest-accepted

#192 Quick Select Algorithm
  quick_select_algorithm.cpp
Labels: Hacktoberfest, hacktoberfest-accepted

#199 2Stacks in an array
  2StackInAnArray.cpp
Labels: Hacktoberfest, hacktoberfest-accepted

#204 Create num_search.cpp
  num_search.cpp
Labels: Hacktoberfest, hacktoberfest-accepted

#203 Create array_sum.cpp
  array_sum.cpp
Labels: Hacktoberfest, hacktoberfest-accepted

#202 Create getBit.cpp
  getBit.cpp
Labels: Hacktoberfest, hacktoberfest-accepted

#201 Create Maximize_Toys.cpp
  Maximize_Toys.cpp
Labels: Hacktoberfest, hacktoberfest-accepted

#200 Create CelsiusToFahrenheit.cpp
  CelsiusToFahrenheit.cpp
Labels: Hacktoberfest, hacktoberfest-accepted

#205 Create distinct_subsequence.cpp
  distinct_subsequence.cpp
Labels: Hacktoberfest, hacktoberfest-accepted
